name: build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: clean
        run: cargo clean

      - name: build for ubuntu
        run: cargo build
        env:
          RUST_BACKTRACE: 1

      - name: test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
      
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: build with wasm-pack
        run: wasm-pack build --target web
