name: build

on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: clean
        run: cargo clean

      - name: build
        run: cargo build
        env:
          RUST_BACKTRACE: 1

      - name: test
        run: cargo test
        env:
          RUST_BACKTRACE: 1
